name: fitness_health_tracker
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  http: ^1.2.0
  shared_preferences: ^2.2.1
  google_fonts: ^5.1.0
  flutter_ruler_picker: ^1.0.6
  intl: ^0.19.0
  table_calendar: ^3.1.3
  pie_chart: ^5.4.0
  fl_chart: ^0.66.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  scroll_date_picker: ^3.8.0
  firebase_storage: ^11.6.9
  image_picker: ^1.0.8
  flutter_local_notifications: ^9.9.1
  file: ^6.1.4
  sqflite: ^2.3.1
  dotted_border: ^2.1.0
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/auth/
    - assets/home/


