// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABAWM3e6eBIWIHbSFhI425XyXJ9V8Z1xE',
    appId: '1:838157311999:android:fb994ec4c9dae2cf8291ca',
    messagingSenderId: '838157311999',
    projectId: 'health-tracker-5d0d9',
    storageBucket: 'health-tracker-5d0d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgo08X0XQ9wIGaMQ0f_0RUvdz3sMprZTI',
    appId: '1:838157311999:ios:41d9406b75de26dd8291ca',
    messagingSenderId: '838157311999',
    projectId: 'health-tracker-5d0d9',
    storageBucket: 'health-tracker-5d0d9.firebasestorage.app',
    iosClientId: '838157311999-29cq8c8qop203dj8huc8rvpnkqsi6l7e.apps.googleusercontent.com',
    iosBundleId: 'com.fitness.fitnesshealthtrackercharles.fitnessHealthTracker',
  );

}